server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # 1. Запрет кэша + ЯДЕРНАЯ ОЧИСТКА
    location /index.html {
        # Эта команда заставит браузер удалить ВСЕ данные сайта при загрузке страницы
        # Оставьте это на 24 часа, потом уберите, иначе пользователям придется логиниться каждый раз
        add_header Clear-Site-Data "cache, storage, executionContexts";
        
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        try_files $uri =404;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Для остальных путей тоже добавляем очистку
    location / {
        try_files $uri $uri/ /index.html;
        add_header Clear-Site-Data "cache, storage, executionContexts";
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0";
    }
}